name: Daily Revenue Payout
on:
  schedule:
    - cron: '0 18 * * *'  # 6PM UTC (8PM SAST)
  workflow_dispatch:

jobs:
  execute-payouts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests stripe python-dotenv
      - name: Run payout router
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_ACCOUNT_ID: ${{ secrets.STRIPE_ACCOUNT_ID }}
          VALR_KEY: ${{ secrets.VALR_KEY }}
          VALR_SECRET: ${{ secrets.VALR_SECRET }}
          TRUST_KEY: ${{ secrets.TRUST_KEY }}
          PAYPAL_ID: ${{ secrets.PAYPAL_ID }}
          FNB_ACCOUNT_NUMBER: ${{ secrets.FNB_ACCOUNT_NUMBER }}
          FNB_ACCOUNT_NAME: ${{ secrets.FNB_ACCOUNT_NAME }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python monetization/payout_router.py
