name: Self-Healing System
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check server status
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.PRODUCTION_URL }}/health)
          if [ $STATUS -ne 200 ]; then
            echo "Server down! Triggering recovery..."
            python ai_agents/error_monitor.py
          fi
      - name: Run code improvement
        run: |
          python ai_agents/code_generator.py --file server/main.py
